#version: '2'
#
#services:
#  app:
#    image: 'wallet:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=postgres
#      - spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
#      - spring.liquibase.change-log=db/changelog/dbchangelog.yaml
#      - spring.liquibase.enabled=true
#  db:
#    image: "postgres:9.6-alpine"
#    container_name: db
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=postgres